=head1 NAME

DBIx::Decorator -

=head1 SYNOPSIS

  use DBIx::Decorator;

=head1 DESCRIPTION

DBIx::Decorator is

=head1 AUTHOR

Takuya Tsuchida E<lt>tsucchi {at} cpan.orgE<gt>

=head1 SEE ALSO

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


=cut

